version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

      - run:
          name: Install VPNC (Cisco VPN)
          command: |
            sudo apt update
            sudo apt install network-manager-vpnc

      - run:
          name: Check IP before VPN connection
          command: |
            ip a
            ip r
            ss -atn
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - run:
          name: Cisco VPN Setup
          command: |

            echo $VPNC_ULL_CONF | base64 --decode > /tmp/ull.conf
            sudo nmcli con import type vpnc file /tmp/ull.conf

            #sudo vpnc-connect --debug 2 ull
            nmcli connection show
            nmcli connection ULL up

            # Configure routes
            #sudo ip route del default dev tun0 
            #sudo ip route add 10.6.128.0/22 dev tun0
            ip r

      - run:
          name: Wait for the connection to be established
          command: sleep 30

      - run:
          name: Check IP after VPN connection
          command: |
            ip a
            ip r
            ss -atn
            cat /etc/resolv.conf
            curl checkip.amazonaws.com
      
      - run:
          name: Run commands in our infrastructure
          command: |
            # A command
            # Another command

      - run:
          name: Disconnect from  CISCO ULL
          command: sudo nmcli connection ULL down || true
          when: always
