version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

      - run:
          name: Run commands in our infrastructure
          command: |
            # A command
            # Another command

