version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: #Install stuff
          name: Update and install
          command: |
            sudo apt update && apt install -y openconnect curl gnupg libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb ca-certificates

      - run:
          name: Run commands in our infrastructure
          command: |
            # A command
            # Another command

